### PR TITLE
 Add support for custom background

### PR DESCRIPTION
**Pull request by gabfiocchi**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [guidelines](https://github.com/fengyuanchen/compressorjs/blob/master/.github/CONTRIBUTING.md#commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update
[ ] Refactor
[ ] Build related changes
[ ] Documentation content changes
[ ] Other, Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
If you have an image in `PNG` and you want is to change the background color and convert to `JPEG`, you can not because the color `#000` is being applied by default. This change accepts the possibility of having a personalized background.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by fengyuanchen** [comment]
Thanks for your PR. But this option is not necessary as you can custom the `fillStyle` in the `beforeDraw` hook function:

```js
new Compressor(file, {
  beforeDraw(context) {
    context.fillStyle = '#fff';
  },
});
```

**Comment by gabfiocchi** [comment]
@fengyuanchen I already tried it and it did not work, it continues applying the background by default, without respecting the hook.

**Comment by gabfiocchi** [comment]
@fengyuanchen with the edition works fine! Thanks

**Comment by fengyuanchen** [comment]
With v1.0.1, the demo code will be more simpler:

```js
new Compressor(file, {
  beforeDraw: function (context, canvas) {
      context.fillStyle = '#fff';
      context.fillRect(0, 0, canvas.width, canvas.height);
    },
});
```

**Pull request closed without merging**
